<?php

class ComplexModel extends \Tecnodesign_Model
{
    public static $schema = [
        'database' => 'firstwww',
        'tableName' => 'teams',
        'className' => 'Tecnodesign\\ComplexModel',
        'columns' => [
            'id' => ['type' => 'int', 'increment' => 'auto', 'null' => false, 'primary' => true,],
            'team_short' => ['type' => 'string', 'size' => '50', 'null' => false,],
            'team' => ['type' => 'string', 'size' => '150', 'null' => false,],
            'host_organization' => ['type' => 'string', 'size' => '255', 'null' => true,],
            'country' => ['type' => 'string', 'size' => '2', 'min-size' => '2', 'null' => true,],
            'country_other' => ['type' => 'string', 'size' => '255', 'null' => true,],
            'date_establishment' => ['type' => 'date', 'null' => true,],
            'constituency_type' => ['type' => 'int', 'null' => true,],
            'constituency_source' => ['type' => 'int', 'null' => true,],
            'constituency_description' => ['type' => 'string', 'size' => '1000', 'null' => true,],
            'constituency_url' => ['type' => 'string', 'size' => '1000', 'null' => true,],
            'constituency_countries' => ['type' => 'string', 'size' => '255', 'null' => true,],
            'phone' => ['type' => 'string', 'size' => '20', 'null' => true,],
            'phone_emergency' => ['type' => 'string', 'size' => '20', 'null' => true,],
            'email' => ['type' => 'string', 'size' => '50', 'null' => true,],
            'fax' => ['type' => 'string', 'size' => '20', 'null' => true,],
            'timezone' => ['type' => 'string', 'size' => '20', 'null' => true,],
            'timezone_dst' => ['type' => 'string', 'size' => '20', 'null' => true,],
            'other_communication' => ['type' => 'string', 'size' => '200', 'null' => true,],
            'address' => ['type' => 'string', 'size' => '200', 'null' => true,],
            'invoice_reference' => ['type' => 'string', 'size' => '100', 'null' => true,],
            'invoice_separate' => ['type' => 'int', 'max' => 128, 'null' => true,],
            'invoice_identifier' => ['type' => 'string', 'size' => '100', 'null' => true,],
            'invoice_person' => ['type' => 'string', 'size' => '150', 'null' => true,],
            'invoice_email' => ['type' => 'string', 'size' => '100', 'null' => true,],
            'address_invoice' => ['type' => 'string', 'size' => '200', 'null' => true,],
            'invoice_country' => ['type' => 'string', 'size' => '2', 'min-size' => '2', 'null' => true,],
            'business_hours' => ['type' => 'string', 'size' => '200', 'null' => true,],
            'no_business_hours_contact' => ['type' => 'string', 'size' => '200', 'null' => true,],
            'reactive_services' => ['type' => 'string', 'size' => '250', 'null' => true,],
            'reactive_services_other' => ['type' => 'string', 'size' => '200', 'null' => true,],
            'proactive_services' => ['type' => 'string', 'size' => '250', 'null' => true,],
            'proactive_services_other' => ['type' => 'string', 'size' => '200', 'null' => true,],
            'quality_services' => ['type' => 'string', 'size' => '250', 'null' => true,],
            'quality_services_other' => ['type' => 'string', 'size' => '200', 'null' => true,],
            'policy_classification' => ['type' => 'string', 'size' => '1000', 'null' => true,],
            'policy_handling' => ['type' => 'string', 'size' => '1000', 'null' => true,],
            'policy_considerations' => ['type' => 'string', 'size' => '1000', 'null' => true,],
            'policy_legal' => ['type' => 'string', 'size' => '1000', 'null' => true,],
            'policy_cryptography' => ['type' => 'string', 'size' => '1000', 'null' => true,],
            'pgp_key' => ['type' => 'string', 'size' => '50', 'null' => true,],
            'pgp_fingerprint' => ['type' => 'string', 'size' => '50', 'null' => true,],
            'pgp_public' => ['type' => 'string', 'size' => '', 'null' => true,],
            'x509_certificates' => ['type' => 'string', 'size' => '', 'null' => true,],
            'qkey_email' => ['type' => 'string', 'size' => '100', 'null' => true,],
            'qkey_key' => ['type' => 'string', 'size' => '50', 'null' => true,],
            'qkey_fingerprint' => ['type' => 'string', 'size' => '50', 'null' => true,],
            'expertise_os' => ['type' => 'string', 'size' => '100', 'null' => true,],
            'expertise_system' => ['type' => 'string', 'size' => '100', 'null' => true,],
            'expertise_networks' => ['type' => 'string', 'size' => '200', 'null' => true,],
            'constituency_contact' => ['type' => 'string', 'size' => '200', 'null' => true,],
            'pgp_key_revocation' => ['type' => 'string', 'size' => '200', 'null' => true,],
            'email_reps' => ['type' => 'string', 'size' => '200', 'null' => true,],
            'email_teams' => ['type' => 'string', 'size' => '200', 'null' => true,],
            'allowed_posters' => ['type' => 'string', 'size' => '200', 'null' => true,],
            'www' => ['type' => 'string', 'size' => 200, 'null' => true,],
            'ftp' => ['type' => 'string', 'size' => 200, 'null' => true,],
            'news' => ['type' => 'string', 'size' => 200, 'null' => true,],
            'mailing_lists' => ['type' => 'string', 'size' => '200', 'null' => true,],
            'representative' => ['type' => 'int', 'null' => true,],
            'representative2' => ['type' => 'int', 'null' => true,],
            'type' => ['type' => 'int', 'null' => false,],
            'additional_remarks' => ['type' => 'string', 'size' => '200', 'null' => true,],
            'status' => ['type' => 'int', 'null' => false, 'default' => 1,],
            'sponsor' => ['type' => 'int', 'null' => true,],
            'sponsor2' => ['type' => 'int', 'null' => true,],
            'status_previous' => ['type' => 'int', 'null' => true,],
            'status_update' => ['type' => 'date', 'null' => true,],
            'status_reason' => ['type' => 'string', 'size' => '200', 'null' => true,],
            'date_verified' => ['type' => 'datetime', 'null' => true,],
            'date_update' => ['type' => 'datetime', 'null' => true,],
            'date_start' => ['type' => 'date', 'null' => true,],
            'end_reason' => ['type' => 'string', 'size' => '200', 'null' => true,],
            'date_end' => ['type' => 'date', 'null' => true,],
            'modified' => ['type' => 'datetime', 'null' => false,],
        ],
        'relations' => [
            'MailingListSubscribers' => [
                'local' => 'id',
                'foreign' => 'team',
                'type' => 'many',
                'className' => 'Tecnodesign\\MailingListSubscribers',
            ],
            'StatusTeams' => [
                'local' => 'status',
                'foreign' => 'id',
                'type' => 'one',
                'className' => 'Tecnodesign\\StatusTeams',
            ],
            'Countries' => [
                'local' => 'country',
                'foreign' => 'id',
                'type' => 'one',
                'className' => 'Tecnodesign\\Countries',
            ],
            'CountryIso' => [
                'local' => 'country',
                'foreign' => 'id',
                'type' => 'one',
                'className' => 'Tecnodesign\\CountryIso',
            ],
            'TeamsCountry' => [
                'local' => 'id',
                'foreign' => 'team',
                'type' => 'many',
                'className' => 'Tecnodesign\\TeamsCountry',
            ],
            'TeamsCountryOther' => [
                'local' => 'id',
                'foreign' => 'team',
                'type' => 'many',
                'className' => 'Tecnodesign\\TeamsCountryOther',
            ],
            'TeamMembers' => [
                'local' => 'id',
                'foreign' => 'team',
                'type' => 'many',
                'className' => 'Tecnodesign\\TeamMembers',
                'params' => ['status!=' => 4],
            ],
            'ConstituencyTypes' => [
                'local' => 'constituency_type',
                'foreign' => 'id',
                'type' => 'one',
                'className' => 'Tecnodesign\\ConstituencyTypes',
            ],
            'ConstituencySources' => [
                'local' => 'constituency_source',
                'foreign' => 'id',
                'type' => 'one',
                'className' => 'Tecnodesign\\ConstituencySources',
            ],
            'Types' => [
                'local' => 'type',
                'foreign' => 'id',
                'type' => 'one',
                'className' => 'Tecnodesign\\Types',
            ],
            'Rep' => [
                'local' => ['representative', 'id'],
                'foreign' => ['id', 'team'],
                'type' => 'one',
                'className' => 'Tecnodesign\\TeamMembers',
            ],
            'Rep2' => [
                'local' => ['representative2', 'id'],
                'foreign' => ['id', 'team'],
                'type' => 'one',
                'className' => 'Tecnodesign\\TeamMembers',
            ],
            'Invoices' => [
                'local' => 'id',
                'foreign' => 'team',
                'type' => 'many',
                'className' => 'Tecnodesign\\Invoices'
            ],
            'TeamCertTypes' => [
                'local' => 'id',
                'foreign' => 'team',
                'type' => 'many',
                'className' => 'Tecnodesign\\TeamCertTypes'
            ],
            'TeamProperties' => [
                'local' => 'id',
                'foreign' => 'team',
                'type' => 'many',
                'className' => 'Tecnodesign\\TeamProperties'
            ],
            'Dues2018' => [
                'local' => 'id',
                'foreign' => 'team',
                'type' => 'many',
                'className' => 'Tecnodesign\\Dues',
                'on' => ['`year`=2018'],
            ],
            'Dues2017' => [
                'local' => 'id',
                'foreign' => 'team',
                'type' => 'many',
                'className' => 'Tecnodesign\\Dues',
                'on' => ['`year`=2017'],
            ],
            'Dues2016' => [
                'local' => 'id',
                'foreign' => 'team',
                'type' => 'many',
                'className' => 'Tecnodesign\\Dues',
                'on' => ['`year`=2016'],
            ],
        ],
        'scope' => [
            'string' => ['team_short'],
            'choices' => ['team_short', 'team'],
        ],
        'events' => [
            'before-insert' => ['actAs', 'checkMembers',],
            'before-update' => ['actAs',],
            'before-delete' => ['actAs', 'disable',],
            'after-update' => ['checkStatus'],
            'after-delete' => ['checkStatus'],
            'after-save' => ['webhooks'],
        ],
        'actAs' => [
            'before-insert' => ['timestampable' => ['modified',],],
            'before-update' => ['timestampable' => ['modified',],],
            'before-delete' => ['timestampable' => ['modified',],],
        ],
        'order' => [
            'team_short' => 'asc',
        ],
        'form' => [
            'team_short' => ['bind' => 'team_short',],
            'team' => ['bind' => 'team',],
            'host_organization' => ['bind' => 'host_organization',],
            'country' => ['bind' => 'country', 'type' => 'select', 'choices' => 'Tecnodesign\\Countries',],
            'country_other' => [
                'bind' => 'country_other',
                'type' => 'select',
                'choices' => 'Tecnodesign\\Countries',
                'multiple' => true,
            ],
            'date_establishment' => ['bind' => 'date_establishment',],
            'constituency_type' => [
                'bind' => 'constituency_type',
                'type' => 'select',
                'choices' => 'Tecnodesign\\ConstituencyTypes',
            ],
            'constituency_source' => [
                'bind' => 'constituency_source',
                'type' => 'select',
                'choices' => 'Tecnodesign\\ConstituencySources',
            ],
            'constituency_description' => ['bind' => 'constituency_description', 'type' => 'textarea',],
            'constituency_url' => ['bind' => 'constituency_url', 'type' => 'textarea',],
            'constituency_countries' => [
                'bind' => 'constituency_countries',
                'type' => 'select',
                'choices' => 'Tecnodesign\\Countries',
                'multiple' => true,
            ],
            'phone' => ['bind' => 'phone',],
            'phone_emergency' => ['bind' => 'phone_emergency',],
            'email' => ['bind' => 'email',],
            'fax' => ['bind' => 'fax',],
            'timezone' => ['bind' => 'timezone',],
            'timezone_dst' => ['bind' => 'timezone_dst',],
            'other_communication' => ['bind' => 'other_communication', 'type' => 'textarea',],
            'address' => ['bind' => 'address', 'type' => 'textarea',],
            'invoice_reference' => ['bind' => 'invoice_reference',],
            'invoice_separate' => [
                'bind' => 'invoice_separate',
                'type' => 'radio',
                'choices' => ['No', 'Yes'],
            ],
            'invoice_identifier' => ['bind' => 'invoice_identifier',],
            'invoice_person' => ['bind' => 'invoice_person',],
            'invoice_email' => ['bind' => 'invoice_email',],
            'address_invoice' => ['bind' => 'address_invoice', 'type' => 'textarea',],
            'invoice_country' => [
                'bind' => 'invoice_country',
                'type' => 'select',
                'choices' => 'Tecnodesign\\Countries',
            ],
            'business_hours' => ['bind' => 'business_hours', 'type' => 'textarea',],
            'no_business_hours_contact' => ['bind' => 'no_business_hours_contact', 'type' => 'textarea',],
            'reactive_services' => [
                'bind' => 'reactive_services',
                'type' => 'select',
                'multiple' => true,
                'choices' => 'Tecnodesign\\ReactiveServices',
            ],
            'reactive_services_other' => ['bind' => 'reactive_services_other',],
            'proactive_services' => [
                'bind' => 'proactive_services',
                'type' => 'select',
                'multiple' => true,
                'choices' => 'Tecnodesign\\ProactiveServices',
            ],
            'proactive_services_other' => ['bind' => 'proactive_services_other',],
            'quality_services' => [
                'bind' => 'quality_services',
                'type' => 'select',
                'multiple' => true,
                'choices' => 'Tecnodesign\\QualityServices',
            ],
            'quality_services_other' => ['bind' => 'quality_services_other',],
            'policy_classification' => ['bind' => 'policy_classification', 'type' => 'textarea',],
            'policy_handling' => ['bind' => 'policy_handling', 'type' => 'textarea',],
            'policy_considerations' => ['bind' => 'policy_considerations', 'type' => 'textarea',],
            'policy_legal' => ['bind' => 'policy_legal', 'type' => 'textarea',],
            'policy_cryptography' => ['bind' => 'policy_cryptography', 'type' => 'textarea',],
            'pgp_key' => ['bind' => 'pgp_key', 'class' => 'i1s2',],
            'pgp_fingerprint' => ['bind' => 'pgp_fingerprint', 'class' => 'i1s2',],
            'pgp_public' => ['bind' => 'pgp_public', 'class' => 'i-mono ih6', 'type' => 'textarea',],
            'x509_certificates' => ['bind' => 'x509_certificates', 'class' => 'i2s3', 'type' => 'textarea',],
            'qkey_email' => ['bind' => 'qkey_email', 'class' => 'i1s2 i-block',],
            'qkey_key' => ['bind' => 'qkey_key', 'class' => 'i1s2 i-block',],
            'qkey_fingerprint' => ['bind' => 'qkey_fingerprint', 'class' => 'i1s2 i-block',],
            'expertise_os' => ['bind' => 'expertise_os',],
            'expertise_system' => ['bind' => 'expertise_system',],
            'expertise_networks' => ['bind' => 'expertise_networks',],
            'constituency_contact' => ['bind' => 'constituency_contact', 'type' => 'textarea',],
            'pgp_key_revocation' => ['bind' => 'pgp_key_revocation', 'type' => 'textarea',],
            'email_reps' => ['bind' => 'email_reps',],
            'email_teams' => ['bind' => 'email_teams',],
            'allowed_posters' => ['bind' => 'allowed_posters', 'type' => 'textarea',],
            'www' => ['bind' => 'www',],
            'ftp' => ['bind' => 'ftp',],
            'news' => ['bind' => 'news',],
            'mailing_lists' => ['bind' => 'mailing_lists',],
            'representative' => [
                'bind' => 'representative',
                'type' => 'select',
                'choices' => 'Tecnodesign\\TeamMembers',
                'class' => 'i1s2',
            ],
            'representative2' => [
                'bind' => 'representative2',
                'type' => 'select',
                'choices' => 'Tecnodesign\\TeamMembers',
            ],
            'type' => ['bind' => 'type', 'type' => 'select', 'choices' => 'Tecnodesign\\Types',],
            'additional_remarks' => ['bind' => 'additional_remarks',],
            'status' => ['bind' => 'status', 'type' => 'select', 'choices' => 'Tecnodesign\\StatusTeams'],
            'status_previous' => [
                'bind' => 'status_previous',
                'type' => 'select',
                'choices' => 'Tecnodesign\\StatusTeams',
            ],
            'sponsor' => [
                'bind' => 'sponsor',
                'type' => 'select',
                'choices' => 'Tecnodesign\\ComplexModel',
                'class' => 'i1s2',
            ],
            'sponsor2' => [
                'bind' => 'sponsor2',
                'type' => 'select',
                'choices' => 'Tecnodesign\\ComplexModel',
                'class' => 'i1s2',
            ],
            'status_update' => ['bind' => 'status_update',],
            'status_reason' => ['bind' => 'status_reason',],
            'date_verified' => ['bind' => 'date_verified',],
            'date_update' => ['bind' => 'date_update',],
            'date_start' => ['bind' => 'date_start',],
            'end_reason' => ['bind' => 'end_reason',],
            'date_end' => ['bind' => 'date_end',],
            'modified' => ['bind' => 'modified',],
        ],
    ];
}
